version: "3"

services:
  my-nginx:
    build: requirements/nginx
    image: my-nginx
    ports: 
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - my-wordpress
    restart: always

  my-mariadb:
    build: requirements/mariadb
    image: my-mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
 
  my-wordpress:
    build: requirements/wordpress
    image: my-wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - my-mariadb
    env_file:
      - .env
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aperin/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aperin/data/wordpress_data
      o: bind

networks:
  inception:
